### ISSUE TITLE
Styled components as peer dependency

### ISSUE THREAD

**Issue by LennardWesterveld** [balena-io-modules/rendition#1005]
**Is your feature request related to a problem? Please describe.**
I want to add some component on my own and use the components of balena-io that isn't possible on the normal way right now also how grommet it is doing.

**Describe the solution you'd like**
I would like that styled-components will be a peer dependency.

**Comment by LucianBuzzo** [comment]
@LennardWesterveld could you provide some more detail about what you are trying to do in your component and why it isn't possible in the "normal way"? I'd like to dig into the problems you're facing.

**Comment by sradevski** [comment]
I will close this due to inactivity. Specifying styled-components as a peer dependency makes sense in certain cases, but having it bundled together with Rendition is much more convenient for users. `npm` and `yarn` are smart enough to decouple and local installation of styled-components as well (as long as the semver matches), so it doesn't add any bloat anyhow. 

If there are more users who find that styled-components should be a peer dependency, we can reopen and reconsider it.
