### ISSUE TITLE
Add integration tests for filters

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#254]
The filter component has the most complex UI and would make a good starting point for a suite of integration tests running on selenium or similar.

**Comment by sradevski** [comment]
@LucianBuzzo I was just checking the Filters component, and it has a pretty good unit test coverage. Since the whole point of rendition is to have independent components, do you think integration tests are necessary on top of the unit + visual tests? I just think it might add additional maintenance complexity without a significant benefit on top of the tests we already have.

**Comment by LucianBuzzo** [comment]
@sradevski This issue was created before we implemented our testing on top of Enzyme. Overall I've been very happy with the combination of Enzyme testing and visual testing. I think it would be good to expand the test coverage in our existing test https://github.com/balena-io-modules/rendition/blob/master/__tests__/components/Filters.spec.js though this is a separate issue.
For now, I think this issue can be closed.
