### ISSUE TITLE
Compile code to es6 modules instead of common js and allow tree shaking 

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#492]
Using es6 modules instead of common js means that tree shaking achieved more easily. Since this a react library we can count on consumers doing some compilation of their own, through babel or another library.

https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking/

**Comment by thgreasi** [comment]
Maybe we could offer both es5 & es6 builds and use the “module” package.json field.

**Comment by thgreasi** [comment]
Here are the: rollup & webpack docs on this field:
* https://github.com/rollup/rollup/wiki/pkg.module
* https://webpack.js.org/guides/author-libraries/#final-steps

This might have to be a breaking change and should not be done w/o extensive testing (it didn't work quite well in localForage), since the various module loaders will suddenly switch their import targets and the pre-existing import methods that the consumers were using might stop working as expected.
