### ISSUE TITLE
NavBar component fails app

### ISSUE THREAD

**Issue by edmundas-ramanauskas** [balena-io-modules/rendition#741]
**Describe the bug**
in latest rendition version (4.49.1) `NavBar` component doesn't work and breaks the app

**To Reproduce**
Just include `NavBar` component anywhere in the app or follow example from storybook:
https://github.com/balena-io-modules/rendition/blob/master/src/stories/NavBar.js

**Expected behavior**
App should display `NavBar` component

**Screenshots**
![image](https://user-images.githubusercontent.com/4420081/52535486-a549e980-2d57-11e9-9bf6-17fe35533a2e.png)
![image](https://user-images.githubusercontent.com/4420081/52535493-b72b8c80-2d57-11e9-9bef-38b62e582601.png)
![image](https://user-images.githubusercontent.com/4420081/52535497-ca3e5c80-2d57-11e9-8821-39768b49c1a3.png)

**Specifications (please complete the following information):**
  - Browser: https://whatsmybrowser.org/b/AF3RDHA
  - OS: Ubuntu 18.10
  - Environment.: development

**Comment by sradevski** [comment]
@edmundas-ramanauskas Thanks for the report. The problem seems to lie in the naming of the component. Although in the documentation it says `NavBar`, the component is actually called `Navbar` in the export (you can see it in the storybook code), therefore the problem you are experiencing. I will update the documentation accordingly.

**Comment by edmundas-ramanauskas** [comment]
right, didn't notice the difference :+1:
