### ISSUE TITLE
Change Txt component to be Text instead

### ISSUE THREAD

**Issue by karaxuna** [balena-io-modules/rendition#812]
Rendition has `Button`, not `Btn` and all other components have full name except `Txt` component. We could create alias and it would be backwards compatible.

**Comment by LucianBuzzo** [comment]
@karaxuna The reason why the component is named `Txt` and not `Text` is because `Text` is a global in a browser environment, see https://developer.mozilla.org/en-US/docs/Web/API/Text/Text
The component was originally called `Text` but was changed to `Txt` as you could end up in situations where linters/TypeScript compilation would give false positives if you didn't import the `Text` component, leading to hard-to-trace bugs.
