### ISSUE TITLE
ArcSlider: SlideEnd or SlideStop event

### ISSUE THREAD

**Issue by doublepithre** [balena-io-modules/rendition#970]
**Is your feature request related to a problem? Please describe.**
We need to have an event which tells us when the user finished sliding(like mouseup) event. Currently, I see that the event listeners are added to the **document**(not sure why). Depending on `onValueChange` method for these types of work is expensive and not usable at all.

**Describe the solution you'd like**
Adding event listeners to just slider element in CDM and removing in CWUM methods
```
if(this.$slider) {
   this.$slider.addEventListener('mouseup', this.handleSlideEnd);
   this.$slider.addEventListener('touchend', this.handleSlideEnd);
   this.$slider.addEventListener('touchcancel', this.handleSlideEnd);
}

And 

handleSlideEnd = () => {
    if(this.props.slideEnd && this.$slider) {
      this.props.slideEnd();
    }
};

```
**Describe alternatives you've considered**
Tried `onValueChange` with throttling

**Comment by LucianBuzzo** [comment]
@doublepithre If you need to run a function once the slider has finished moving, using a `debounce` function ( https://lodash.com/docs/4.17.15#debounce ) is typically the best method. I'd much rather keep the API lightweight and let the user choose their own method of handling this then introducing additional properties to this component.

With regards to the `document` listeners, you'll notice that the `mousedown`/`touchstart` events are bound to the component itself, but the `move`/`end` events are not. This is because we want the drag behaviour to only start with an event on the component, but drag handling should continuously work wherever you move the cursor in the document. For example, If we bind the "end" events directly to the component, the action wouldn't end unless you move the cursor back inside the components bounding box.

**Comment by doublepithre** [comment]
@LucianBuzzo I had tried a combination of both debounce and throttling to get the desired result but I thought it was a hacky way. I agree with your point on keeping the API lightweight.

> the action wouldn't end unless you move the cursor back inside the components bounding box.

Ah! I see I didn't think of this.

**Comment by mfazer** [comment]
Similar case:
`<ArcSlider/>` **onMouseUp** on desktop doesn't trigger the event outside the element.
I think expected behavior by the end-user is to trigger the event anyway (nice UX).

![image](https://user-images.githubusercontent.com/17722512/67950120-63b0e580-fbe9-11e9-9c09-db47130dc5b2.png)

What's your opinion?
Shall we re-open or report a new issue?

**Comment by LucianBuzzo** [comment]
@mfazer I still stand by my earlier comment about keeping the API lightweight. I'm also against hijacking the `onMouseUp` handler to behave differently on this component as we start opaquely modifying expected behaviour. In this case the expected behaviour of `onMouseUp` is that it will fire when the user triggers a `mouseup` event on the component in question.
